### ISSUE TITLE
[BUG] The file is smaller than the orignal THP.

### ISSUE THREAD

**Issue by radianthero** [Lord-Giganticus/THP-Conveter#10]
**Describe the bug**
File sizes aren't exact.

This might be a specific issue for the game I'm trying to mod, it's a Lupin III GameCube game, and for disc 2 it only really uses tmp files as fmvs. I think because the files aren't the same file size for the original is 784 MB, where as when I convert to MP4, then straight back to tmp without any changes done to it, it ends up being 768 MB, Causing the game to crash. 

**To Reproduce**
Grab an original tmp file, convert to mp4 using your program, then go back to tmp, see file sizes.

**Expected behavior**
Be closer to file size.

**Additional context**
I'm sure the program itself is working fine, vlc opens the tmp converted just fine and it seems to be the exact file size, though vlc doesn't say. the original resolution of the file is odd, at a resolution of 640x352, and the converter says it should be done in multiples of 16, that my be causing the issue? Just guessing here.

**Comment by Lord-Giganticus** [comment]
😕 uhh- im a tad confused, thpconv itself is mega jank

**Comment by radianthero** [comment]
I ended up figuring it out. The thp the game expects is 1.0, yours (and most) converters are using the 1.1. WiiFlowThp uses 1.0, and after that I lowered the sample rate through ffmeg.

If you wanted to add compatibility, could include both versions.

**Comment by Lord-Giganticus** [comment]
Ah, I see. I'd need to get my hands on a 1.0 thpconv for that.
