### ISSUE TITLE
[BUG] Lower Pitched audio

### ISSUE THREAD

**Issue by Lord-Giganticus** [Lord-Giganticus/THP-Conveter#3]
There appears to be a issue when adding audio to a thp, it is pitched  low pretty severely...

This is likely a issue with mplayer but modern versions of it don't even work.

Anyone with info is welcome to comment.

**Comment by jonko0493** [comment]
Is there a reason for not just using ffmpeg for this? In my testing `ffmpeg -i video.thp audio.wav` works great.

**Comment by Lord-Giganticus** [comment]
> Is there a reason for not just using ffmpeg for this? In my testing `ffmpeg -i video.thp audio.wav` works great.

I had meant the audio playing from the THP on a actual console.. I'll do some testing to pinpoint the issue
