### ISSUE TITLE
[BUG] Spelling error in the repository name

### ISSUE THREAD

**Issue by Panquesito7** [Lord-Giganticus/THP-Conveter#7]
### Description

The repository name seems to be missing an `r`.
Currently, it says `Conveter`, and should be `Converter`.

In case you rename the repository, everyone will be redirected, so you don't have to worry about that. For more information: https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by Lord-Giganticus** [comment]
Done, thanks for pointing this out.
