### ISSUE TITLE
THPConverter website 404 error

### ISSUE THREAD

**Issue by Captainkittyca2** [Lord-Giganticus/THP-Conveter#9]
**Describe the bug**
When going to your github.io and then clicking on the link to THPConverter, i get 404 error. https://lord-giganticus.github.io/THP-Conveter/

**To Reproduce**
1. Go to the github.io of you.
2. Click on THP-Converter link.
3. ????
4. 404 error. :D

**Expected behavior**
I expected to be taken to the THP-Converter section of the github.io.

**Screenshots**
![image](https://github.com/Lord-Giganticus/THP-Converter/assets/68467449/6314c256-4bb5-49af-a905-559ec7191ab6)

**Additional context**
I want to convert thp files to mp4 and convert mp4 files to thp.

**Comment by Lord-Giganticus** [comment]
Oh, that's... weird. That stuff is rather outdated so i'll take a look

**Comment by lurmirari** [comment]
it seems that it's just a typo, the link in the github says "Conveter" instead of "Converter" (notice the missing r before the t), adding the missing r in the url bar took me to the site correctly

**Comment by Captainkittyca2** [comment]
tool is dope

**Comment by Lord-Giganticus** [comment]
oh yea i DID rename the repo so it may be that, idk

**Comment by Lord-Giganticus** [comment]
fixed.
